#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias flushdns='dscacheutil -flushcache;sudo killall -HUP mDNSResponder'
alias breakfast='screen /dev/cu.usbserial 9600'
alias ec2ssh='ssh -i ~/.ssh/aws2014'

